# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui/FieldBox.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(903, 646)
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 220, 901, 401))
        self.tabWidget.setMovable(False)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.na = QtGui.QWidget()
        self.na.setObjectName(_fromUtf8("na"))
        self.qwtPlot_2 = QwtPlot(self.na)
        self.qwtPlot_2.setGeometry(QtCore.QRect(0, 0, 641, 331))
        self.qwtPlot_2.setObjectName(_fromUtf8("qwtPlot_2"))
        self.formLayoutWidget_2 = QtGui.QWidget(self.na)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(680, 30, 201, 141))
        self.formLayoutWidget_2.setObjectName(_fromUtf8("formLayoutWidget_2"))
        self.formLayout_2 = QtGui.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.pushButton_4 = QtGui.QPushButton(self.formLayoutWidget_2)
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.pushButton_4)
        self.tabWidget.addTab(self.na, _fromUtf8(""))
        self.phase = QtGui.QWidget()
        self.phase.setObjectName(_fromUtf8("phase"))
        self.phasePlot = QwtPlot(self.phase)
        self.phasePlot.setGeometry(QtCore.QRect(0, 0, 641, 331))
        self.phasePlot.setObjectName(_fromUtf8("phasePlot"))
        self.frameNA = QtGui.QFrame(self.phase)
        self.frameNA.setGeometry(QtCore.QRect(640, 0, 261, 301))
        self.frameNA.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frameNA.setFrameShadow(QtGui.QFrame.Raised)
        self.frameNA.setObjectName(_fromUtf8("frameNA"))
        self.nnnn = QtGui.QLabel(self.frameNA)
        self.nnnn.setGeometry(QtCore.QRect(110, 10, 59, 14))
        self.nnnn.setObjectName(_fromUtf8("nnnn"))
        self.verticalLayoutWidget_3 = QtGui.QWidget(self.frameNA)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(10, 50, 123, 62))
        self.verticalLayoutWidget_3.setObjectName(_fromUtf8("verticalLayoutWidget_3"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.btnPhase = QtGui.QPushButton(self.verticalLayoutWidget_3)
        self.btnPhase.setObjectName(_fromUtf8("btnPhase"))
        self.verticalLayout_3.addWidget(self.btnPhase)
        self.btnMeasurePh = QtGui.QPushButton(self.frameNA)
        self.btnMeasurePh.setGeometry(QtCore.QRect(150, 50, 89, 41))
        self.btnMeasurePh.setAutoDefault(False)
        self.btnMeasurePh.setDefault(False)
        self.btnMeasurePh.setFlat(False)
        self.btnMeasurePh.setObjectName(_fromUtf8("btnMeasurePh"))
        self.btnFFT = QtGui.QPushButton(self.frameNA)
        self.btnFFT.setGeometry(QtCore.QRect(20, 120, 101, 41))
        self.btnFFT.setObjectName(_fromUtf8("btnFFT"))
        self.btnIFFT = QtGui.QPushButton(self.frameNA)
        self.btnIFFT.setGeometry(QtCore.QRect(130, 120, 101, 41))
        self.btnIFFT.setObjectName(_fromUtf8("btnIFFT"))
        self.btnPrueba = QtGui.QPushButton(self.frameNA)
        self.btnPrueba.setGeometry(QtCore.QRect(100, 210, 89, 27))
        self.btnPrueba.setObjectName(_fromUtf8("btnPrueba"))
        self.btnClear = QtGui.QPushButton(self.phase)
        self.btnClear.setGeometry(QtCore.QRect(740, 320, 89, 27))
        self.btnClear.setObjectName(_fromUtf8("btnClear"))
        self.tabWidget.addTab(self.phase, _fromUtf8(""))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.qwtPlot = QwtPlot(self.tab)
        self.qwtPlot.setGeometry(QtCore.QRect(10, 10, 641, 331))
        self.qwtPlot.setObjectName(_fromUtf8("qwtPlot"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.Frecuency = QtGui.QFrame(self.centralwidget)
        self.Frecuency.setGeometry(QtCore.QRect(20, 20, 161, 191))
        self.Frecuency.setFrameShape(QtGui.QFrame.StyledPanel)
        self.Frecuency.setFrameShadow(QtGui.QFrame.Raised)
        self.Frecuency.setObjectName(_fromUtf8("Frecuency"))
        self.formLayoutWidget = QtGui.QWidget(self.Frecuency)
        self.formLayoutWidget.setGeometry(QtCore.QRect(0, 40, 160, 114))
        self.formLayoutWidget.setObjectName(_fromUtf8("formLayoutWidget"))
        self.formLayout = QtGui.QFormLayout(self.formLayoutWidget)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.formLayout.setFormAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.QLinitfreq = QtGui.QLabel(self.formLayoutWidget)
        self.QLinitfreq.setAlignment(QtCore.Qt.AlignCenter)
        self.QLinitfreq.setObjectName(_fromUtf8("QLinitfreq"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.QLinitfreq)
        self.QlendFreq = QtGui.QLabel(self.formLayoutWidget)
        self.QlendFreq.setObjectName(_fromUtf8("QlendFreq"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.QlendFreq)
        self.endFreq = QtGui.QLineEdit(self.formLayoutWidget)
        self.endFreq.setText(_fromUtf8(""))
        self.endFreq.setObjectName(_fromUtf8("endFreq"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.endFreq)
        self.iniFreq = QtGui.QLineEdit(self.formLayoutWidget)
        self.iniFreq.setText(_fromUtf8(""))
        self.iniFreq.setObjectName(_fromUtf8("iniFreq"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.iniFreq)
        self.setFreq = QtGui.QPushButton(self.Frecuency)
        self.setFreq.setGeometry(QtCore.QRect(40, 160, 89, 27))
        self.setFreq.setObjectName(_fromUtf8("setFreq"))
        self.freqRange = QtGui.QLabel(self.Frecuency)
        self.freqRange.setGeometry(QtCore.QRect(50, 10, 71, 16))
        self.freqRange.setObjectName(_fromUtf8("freqRange"))
        self.verticalLayoutWidget = QtGui.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(190, 0, 101, 111))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.power = QtGui.QLabel(self.verticalLayoutWidget)
        self.power.setAlignment(QtCore.Qt.AlignCenter)
        self.power.setObjectName(_fromUtf8("power"))
        self.verticalLayout.addWidget(self.power)
        self.powerStep = QtGui.QSpinBox(self.verticalLayoutWidget)
        self.powerStep.setMinimum(-45)
        self.powerStep.setMaximum(3)
        self.powerStep.setProperty("value", -15)
        self.powerStep.setObjectName(_fromUtf8("powerStep"))
        self.verticalLayout.addWidget(self.powerStep)
        self.btnpwstep = QtGui.QPushButton(self.verticalLayoutWidget)
        self.btnpwstep.setObjectName(_fromUtf8("btnpwstep"))
        self.verticalLayout.addWidget(self.btnpwstep)
        self.frame_2 = QtGui.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(440, 10, 451, 221))
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.horizontalLayoutWidget = QtGui.QWidget(self.frame_2)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(30, 40, 300, 51))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.btnOpen = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.btnOpen.setObjectName(_fromUtf8("btnOpen"))
        self.horizontalLayout.addWidget(self.btnOpen)
        self.btnclose = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.btnclose.setObjectName(_fromUtf8("btnclose"))
        self.horizontalLayout.addWidget(self.btnclose)
        self.log = QtGui.QPlainTextEdit(self.frame_2)
        self.log.setGeometry(QtCore.QRect(10, 100, 431, 111))
        self.log.setReadOnly(True)
        self.log.setPlainText(_fromUtf8(""))
        self.log.setObjectName(_fromUtf8("log"))
        self.CN = QtGui.QLabel(self.frame_2)
        self.CN.setGeometry(QtCore.QRect(140, 10, 111, 16))
        self.CN.setObjectName(_fromUtf8("CN"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 903, 22))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.pushButton_4.setText(_translate("MainWindow", "AutoScale", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.na), _translate("MainWindow", "NA-Mode", None))
        self.nnnn.setText(_translate("MainWindow", "Options", None))
        self.btnPhase.setText(_translate("MainWindow", "Load Phase Trace", None))
        self.btnMeasurePh.setText(_translate("MainWindow", "Measure", None))
        self.btnFFT.setText(_translate("MainWindow", "FFT", None))
        self.btnIFFT.setText(_translate("MainWindow", "IFFT", None))
        self.btnPrueba.setText(_translate("MainWindow", "PRUEBA **", None))
        self.btnClear.setText(_translate("MainWindow", "Clear Plot", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.phase), _translate("MainWindow", "Phase", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Page", None))
        self.QLinitfreq.setText(_translate("MainWindow", "IInicio", None))
        self.QlendFreq.setText(_translate("MainWindow", "Final", None))
        self.setFreq.setText(_translate("MainWindow", "Set", None))
        self.freqRange.setText(_translate("MainWindow", "Frecuencia", None))
        self.power.setText(_translate("MainWindow", "Potencia", None))
        self.btnpwstep.setText(_translate("MainWindow", "set", None))
        self.btnOpen.setText(_translate("MainWindow", "Open", None))
        self.btnclose.setText(_translate("MainWindow", "Close", None))
        self.CN.setText(_translate("MainWindow", "Connection", None))

from PyQt4.Qwt5 import QwtPlot
